### ISSUE TITLE
非常感谢我好好看看

### ISSUE THREAD

**Issue by wupj1993** [colddew/micro-service#2]
Creating a new SqlSession

**Comment by wupj1993** [comment]
首先非常感谢你的指导。我大概也配置了下。
再者有几个问题希望和你探讨下，
1.这种的配置方法事务没法被spring管理，我也遇到这个问题，困扰一天
2.每执行2次相同的函数（eg：selectById）都会去数据库查询一次，这明显不是我们愿意看到的，这样数据库明显会撑不住，mybatis的一级缓存没有生效？
3.在二的基础上因为他每次都会创建一个session
4.日志：
第一次查询：
 edu.ustc.server.controller.PersonController - invoke get method...
21:25:28.030 [http-nio-8080-exec-6] DEBUG org.mybatis.spring.SqlSessionUtils - Creating a new SqlSession
21:25:28.037 [http-nio-8080-exec-6] DEBUG org.mybatis.spring.SqlSessionUtils - SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@7fc29b4e] was not registered for synchronization because synchronization is not active
21:25:28.050 [http-nio-8080-exec-6] DEBUG org.springframework.jdbc.datasource.DataSourceUtils - Fetching JDBC Connection from DataSource
21:25:28.513 [http-nio-8080-exec-6] DEBUG org.mybatis.spring.transaction.SpringManagedTransaction - JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@6ff333b8] will not be managed by Spring
21:25:28.519 [http-nio-8080-exec-6] DEBUG edu.ustc.server.mapper.PersonMapper.selectById - ==>  Preparing: select id, name, age from person where id = ? 
21:25:28.712 [http-nio-8080-exec-6] DEBUG edu.ustc.server.mapper.PersonMapper.selectById - ==> Parameters: 1(Integer)
21:25:28.778 [http-nio-8080-exec-6] DEBUG edu.ustc.server.mapper.PersonMapper.selectById - <==      Total: 1
21:25:28.780 [http-nio-8080-exec-6] DEBUG org.mybatis.spring.SqlSessionUtils - Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@7fc29b4e]
21:25:28.780 [http-nio-8080-exec-6] DEBUG org.springframework.jdbc.datasource.DataSourceUtils - Returning JDBC Connection to DataSource
第二次查询：
21:25:36.852 [http-nio-8080-exec-9] DEBUG org.mybatis.spring.SqlSessionUtils - Creating a new SqlSession
21:25:36.852 [http-nio-8080-exec-9] DEBUG org.mybatis.spring.SqlSessionUtils - SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@1a80af62] was not registered for synchronization because synchronization is not active
21:25:36.852 [http-nio-8080-exec-9] DEBUG org.springframework.jdbc.datasource.DataSourceUtils - Fetching JDBC Connection from DataSource
21:25:36.852 [http-nio-8080-exec-9] DEBUG org.mybatis.spring.transaction.SpringManagedTransaction - JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@6ff333b8] will not be managed by Spring
21:25:36.852 [http-nio-8080-exec-9] DEBUG edu.ustc.server.mapper.PersonMapper.selectById - ==>  Preparing: select id, name, age from person where id = ? 
21:25:36.852 [http-nio-8080-exec-9] DEBUG edu.ustc.server.mapper.PersonMapper.selectById - ==> Parameters: 1(Integer)
21:25:36.854 [http-nio-8080-exec-9] DEBUG edu.ustc.server.mapper.PersonMapper.selectById - <==      Total: 1
21:25:36.854 [http-nio-8080-exec-9] DEBUG org.mybatis.spring.SqlSessionUtils - Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@1a80af62]
21:25:36.854 [http-nio-8080-exec-9] DEBUG org.springframework.jdbc.datasource.DataSourceUtils - Returning JDBC Connection to DataSource

我的日志配置：
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <appender name="stdout" class="ch.qos.logback.core.ConsoleAppender">
        <layout class="ch.qos.logback.classic.PatternLayout">
            <pattern>%-20(%d{HH:mm:ss.SSS} [%thread]) %-5level %logger{80} - %msg%n</pattern>
        </layout>
    </appender>
    <appender name="file" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>F:\logs\ijiuwen.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>F:\logs\vnetoo.%d{yyyy-MM-dd}.log.zip</fileNamePattern>
            <maxHistory>30</maxHistory>
            <timeBasedFileNamingAndTriggeringPolicy  class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
                <maxFileSize>100MB</maxFileSize>
            </timeBasedFileNamingAndTriggeringPolicy>
        </rollingPolicy>
        <layout class="ch.qos.logback.classic.PatternLayout">
            <pattern>%-20(%d{HH:mm:ss.SSS} [%thread]) %-5level %logger{80} - %msg%n</pattern>
        </layout>
    </appender>

```
<!-- jdk log  -->
<!--<logger name="java.beans" level="DEBUG" />-->
<!-- struts log  -->
<logger name="logback"/>

<logger name="java.sql.PreparedStatement" level="DEBUG" />
<!--<logger name="org.mybatis.spring" level="DEBUG" />-->
<!--<logger name="org.apache.ibatis" level="DEBUG" />-->
<!--<logger name="java.sql.Connection" level="DEBUG" />-->
<!--<logger name="java.sql.Statement" level="DEBUG" />-->
<!--<logger name="java.sql.PreparedStatement" level="DEBUG" />-->
<!--<logger name="java.sql.ResultSet" level="DEBUG" />-->

<root level="DEBUG">
    <appender-ref ref="stdout" />
</root>
```

</configuration>

**Comment by colddew** [comment]
问题1：DatasourceConfig.java里的transactionManager()方法已经加入了spring事务管理，不理解你说的不起作用的意思

问题2和3：我的理解是，对于一次selectById调用执行完毕session已经关闭，如果需要使用一级缓存应该需要手动控制session的关闭，具体的我想你可以再研究下mybatis一级和二级缓存的实现和使用方式

另外，关于缓存在实际的业务环境中我们通常会考虑使用redis和memcache，mybatis的缓存通常不是我们重点考虑的问题

**Comment by wupj1993** [comment]
谢谢的回答，今天经过查阅大概有些了解了，mybatis一级缓存在和spring中是不顶用的，具体我可能表达不太好，二级缓存一般能不用就不用。确实缓存用今天用了ehcache，现在再研究下redis，再次表示感谢。
